# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  code-coverage: lewisnotestine/java-coverage-gate-orb@2.0.7

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  code-coverage-example-workflow:
    jobs:
      - code-coverage/run_and_save_test_coverage
      - code-coverage/evaluate_test_coverage:
          branch_name: << pipeline.git.branch >>
          requires:
            - code-coverage/run_and_save_test_coverage
